Add Android.bp for 22.5.2
intel/gmmlib pull request #122
Opened 2024-09-25 06:40 UTC by JeevakaPrabu

Test: make libgmm_umd for x86_64

Change-Id: Ib89115762b31dfe1002a276b7cb409d4998af767

2024-09-30 15:36 UTC, theandi666 approved these changes
LGTM

2024-10-08 02:13 UTC, andrescj-chromium requested changes
Looks good to me with changes. Thanks!

2024-10-08 02:13 UTC, andrescj-chromium commented on Android.bp
> +        "-Wno-parentheses-equality",
I tried building without the following flags that I didn't find in the current system, and it works. Consider removing them from here:

- `-Wno-parentheses-equality`
- `-Wno-logical-not-parentheses`
- `-Wno-missing-field-initializers`

2024-10-08 04:06 UTC, JeevakaPrabu commented on Android.bp
> +        "-Wno-unknown-pragmas",
no issues seen even when not present in cflags

2024-10-08 04:07 UTC, JeevakaPrabu commented on Android.bp
> +        "-Wno-missing-braces",
no issues seen even when not present in cflags

2024-10-08 04:07 UTC, JeevakaPrabu commented on Android.bp
> +        "-pthread",
will move it to cppflags

2024-10-09 18:04 UTC, andrescj-chromium approved these changes
Looks good to me. Also tested locally for aosp_cf_x86_64_phone. Thanks!

2024-11-05 16:28 UTC, johnmach commented
Merged in c743f06b430fab6debcb9e0bf82131636e4ede7b

2024-11-05 16:28 UTC, closed without merging